### ISSUE TITLE
v 2.0.9 error on express router all

### ISSUE THREAD

**Issue by marktomm** [BolajiOlajide/koii#23]
The following code will fail
```javascript
const express = require('express');
const router = express.Router();

router.all('/path/to/url', (req, res) => {
  // ...
  res.send({ status: 'done' });
});
```

Because of router.**all**

With error:
```
/home/mark/Development/kusmis/kusmis-core/node_modules/koii/src/utils.js:58
            const httpMethod = method.toUpperCase();
                                      ^

TypeError: Cannot read property 'toUpperCase' of undefined
    at /home/mark/Development/kusmis/kusmis-core/node_modules/koii/src/utils.js:58:39
    at Array.forEach (<anonymous>)
    at /home/mark/Development/kusmis/kusmis-core/node_modules/koii/src/utils.js:56:29
    at Array.forEach (<anonymous>)
    at /home/mark/Development/kusmis/kusmis-core/node_modules/koii/src/utils.js:54:20
    at Array.forEach (<anonymous>)
    at exports.getRoutes (/home/mark/Development/kusmis/kusmis-core/node_modules/koii/src/utils.js:33:15)
    at Function.displayRoutes (/home/mark/Development/kusmis/kusmis-core/node_modules/koii/src/index.js:25:20)
    at Function.emit (node:events:390:22)
    at Function.<anonymous> (/home/mark/Development/kusmis/kusmis-core/node_modules/express/lib/application.js:238:8)
```

**Comment by BolajiOlajide** [comment]
I'm going to close this due to inactivity. I've tested extensively and pushed a new version, so if this issue persists feel free to open another issue. Thanks.
